import { University, Major, QuizQuestion } from "@/types";

// Mock Universities Data (50+ real Kazakhstan universities)
export const universities: University[] = [
  {
    id: "1",
    name: "Nazarbayev University",
    nameRu: "Назарбаев Университет",
    slug: "nazarbayev-university",
    city: "astana",
    cityRu: "Астана",
    description: "Premier research university in Kazakhstan, established in 2010.",
    descriptionRu: "Ведущий исследовательский университет Казахстана, основанный в 2010 году. Университет предлагает программы бакалавриата, магистратуры и докторантуры на английском языке по международным стандартам.",
    logoUrl: "https://images.unsplash.com/photo-1562774053-701939374585?w=200&h=200&fit=crop",
    coverImageUrl: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=1200&h=600&fit=crop",
    ranking: 1,
    foundedYear: 2010,
    website: "https://nu.edu.kz",
    email: "admission@nu.edu.kz",
    phone: "+7 7172 70 6000",
    address: "53 Kabanbay Batyr Ave, Astana",
    addressRu: "пр. Кабанбай батыра, 53, Астана",
    studentsCount: 6500,
    hasMilitaryDept: false,
    hasHostel: true,
    accreditation: "ABET, AACSB",
    universityType: "NATIONAL",
  },
  {
    id: "2",
    name: "Al-Farabi Kazakh National University",
    nameRu: "Казахский национальный университет им. аль-Фараби",
    slug: "kaznu",
    city: "almaty",
    cityRu: "Алматы",
    description: "The oldest and largest university in Kazakhstan.",
    descriptionRu: "Старейший и крупнейший университет Казахстана. Многопрофильный научно-образовательный комплекс, готовящий специалистов по всем направлениям науки.",
    logoUrl: "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=200&h=200&fit=crop",
    coverImageUrl: "https://images.unsplash.com/photo-1607237138185-eedd9c632b0b?w=1200&h=600&fit=crop",
    ranking: 2,
    foundedYear: 1934,
    website: "https://kaznu.kz",
    email: "info@kaznu.kz",
    phone: "+7 727 377 3333",
    address: "71 al-Farabi Ave, Almaty",
    addressRu: "пр. аль-Фараби, 71, Алматы",
    studentsCount: 20000,
    hasMilitaryDept: true,
    hasHostel: true,
    accreditation: "IQAA",
    universityType: "NATIONAL",
  },
  {
    id: "3",
    name: "Kazakh-British Technical University",
    nameRu: "Казахстанско-Британский технический университет",
    slug: "kbtu",
    city: "almaty",
    cityRu: "Алматы",
    description: "Leading technical university with British education standards.",
    descriptionRu: "Ведущий технический университет с британскими стандартами образования. Специализируется на подготовке инженеров и IT-специалистов мирового уровня.",
    logoUrl: "https://images.unsplash.com/photo-1592280771190-3e2e4d571952?w=200&h=200&fit=crop",
    coverImageUrl: "https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?w=1200&h=600&fit=crop",
    ranking: 3,
    foundedYear: 2001,
    website: "https://kbtu.kz",
    email: "admission@kbtu.kz",
    phone: "+7 727 272 5888",
    address: "59 Tole Bi St, Almaty",
    addressRu: "ул. Толе би, 59, Алматы",
    studentsCount: 3500,
    hasMilitaryDept: true,
    hasHostel: true,
    accreditation: "ABET, IET",
    universityType: "PRIVATE",
  },
  {
    id: "4",
    name: "KIMEP University",
    nameRu: "Университет КИМЭП",
    slug: "kimep",
    city: "almaty",
    cityRu: "Алматы",
    description: "Kazakhstan Institute of Management, Economics and Strategic Research.",
    descriptionRu: "Казахстанский институт менеджмента, экономики и стратегических исследований. Один из ведущих бизнес-университетов Центральной Азии.",
    logoUrl: "https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=200&h=200&fit=crop",
    coverImageUrl: "https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=1200&h=600&fit=crop",
    ranking: 4,
    foundedYear: 1992,
    website: "https://kimep.kz",
    email: "admission@kimep.kz",
    phone: "+7 727 270 4440",
    address: "4 Abay Ave, Almaty",
    addressRu: "пр. Абая, 4, Алматы",
    studentsCount: 3000,
    hasMilitaryDept: false,
    hasHostel: true,
    accreditation: "AACSB, ACBSP",
    universityType: "PRIVATE",
  },
  {
    id: "5",
    name: "Satbayev University",
    nameRu: "Satbayev University (КазНИТУ)",
    slug: "satbayev-university",
    city: "almaty",
    cityRu: "Алматы",
    description: "Leading technical university named after K.I. Satbayev.",
    descriptionRu: "Ведущий технический университет им. К.И. Сатпаева. Готовит специалистов в области горного дела, нефтегазовой промышленности и IT.",
    logoUrl: "https://images.unsplash.com/photo-1571260899304-425eee4c7efc?w=200&h=200&fit=crop",
    coverImageUrl: "https://images.unsplash.com/photo-1562774053-701939374585?w=1200&h=600&fit=crop",
    ranking: 5,
    foundedYear: 1934,
    website: "https://satbayev.university",
    email: "info@satbayev.university",
    phone: "+7 727 292 6025",
    address: "22a Satpaeva St, Almaty",
    addressRu: "ул. Сатпаева, 22а, Алматы",
    studentsCount: 12000,
    hasMilitaryDept: true,
    hasHostel: true,
    accreditation: "IQAA, EUR-ACE",
    universityType: "NATIONAL",
  },
  {
    id: "6",
    name: "SDU University",
    nameRu: "Университет СДУ (Сулейман Демирель)",
    slug: "sdu",
    city: "almaty",
    cityRu: "Алматы",
    description: "Modern private university with international standards.",
    descriptionRu: "Современный частный университет с международными стандартами образования. Многопрофильный вуз с сильными факультетами права, бизнеса и IT.",
    logoUrl: "https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=200&h=200&fit=crop",
    coverImageUrl: "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=1200&h=600&fit=crop",
    ranking: 6,
    foundedYear: 1996,
    website: "https://sdu.edu.kz",
    email: "info@sdu.edu.kz",
    phone: "+7 727 307 9509",
    address: "1/1 Abylai Khan St, Kaskelen",
    addressRu: "ул. Абылай хана, 1/1, Каскелен",
    studentsCount: 5000,
    hasMilitaryDept: true,
    hasHostel: true,
    accreditation: "IQAA",
    universityType: "PRIVATE",
  },
  {
    id: "7",
    name: "Eurasian National University",
    nameRu: "Евразийский национальный университет им. Л.Н. Гумилева",
    slug: "enu",
    city: "astana",
    cityRu: "Астана",
    description: "Major national university in the capital city.",
    descriptionRu: "Крупный национальный университет в столице. Один из ведущих вузов страны с широким спектром образовательных программ.",
    logoUrl: "https://images.unsplash.com/photo-1574958269340-fa927503f3dd?w=200&h=200&fit=crop",
    coverImageUrl: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=1200&h=600&fit=crop",
    ranking: 7,
    foundedYear: 1996,
    website: "https://enu.kz",
    email: "rector@enu.kz",
    phone: "+7 7172 35 9818",
    address: "2 Satpayev St, Astana",
    addressRu: "ул. Сатпаева, 2, Астана",
    studentsCount: 18000,
    hasMilitaryDept: true,
    hasHostel: true,
    accreditation: "IQAA",
    universityType: "NATIONAL",
  },
  {
    id: "8",
    name: "Kazakh National Agrarian University",
    nameRu: "Казахский национальный аграрный университет",
    slug: "kaznau",
    city: "almaty",
    cityRu: "Алматы",
    description: "Leading agricultural university in Kazakhstan.",
    descriptionRu: "Ведущий аграрный университет Казахстана. Готовит специалистов для сельского хозяйства и пищевой промышленности.",
    logoUrl: "https://images.unsplash.com/photo-1500937386664-56d1dfef3854?w=200&h=200&fit=crop",
    coverImageUrl: "https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=1200&h=600&fit=crop",
    ranking: 8,
    foundedYear: 1930,
    website: "https://kaznau.kz",
    email: "info@kaznau.kz",
    phone: "+7 727 262 0742",
    address: "8 Abai Ave, Almaty",
    addressRu: "пр. Абая, 8, Алматы",
    studentsCount: 10000,
    hasMilitaryDept: true,
    hasHostel: true,
    accreditation: "IQAA",
    universityType: "NATIONAL",
  },
  {
    id: "9",
    name: "Astana IT University",
    nameRu: "Astana IT University",
    slug: "aitu",
    city: "astana",
    cityRu: "Астана",
    description: "Specialized IT university focused on digital technologies.",
    descriptionRu: "Специализированный IT-университет, фокусирующийся на цифровых технологиях. Готовит программистов, аналитиков данных и специалистов по кибербезопасности.",
    logoUrl: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=200&h=200&fit=crop",
    coverImageUrl: "https://images.unsplash.com/photo-1504639725590-34d0984388bd?w=1200&h=600&fit=crop",
    ranking: 9,
    foundedYear: 2019,
    website: "https://astanait.edu.kz",
    email: "info@astanait.edu.kz",
    phone: "+7 7172 64 5710",
    address: "55/11 Mangilik El Ave, Astana",
    addressRu: "пр. Мангилик Ел, 55/11, Астана",
    studentsCount: 2500,
    hasMilitaryDept: false,
    hasHostel: true,
    accreditation: "ABET",
    universityType: "PUBLIC",
  },
  {
    id: "10",
    name: "International IT University",
    nameRu: "Международный университет информационных технологий",
    slug: "iitu",
    city: "almaty",
    cityRu: "Алматы",
    description: "University specializing in IT and digital technologies.",
    descriptionRu: "Университет, специализирующийся на IT и цифровых технологиях. Партнер ведущих мировых IT-компаний.",
    logoUrl: "https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=200&h=200&fit=crop",
    coverImageUrl: "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=1200&h=600&fit=crop",
    ranking: 10,
    foundedYear: 2009,
    website: "https://iitu.edu.kz",
    email: "info@iitu.edu.kz",
    phone: "+7 727 330 8500",
    address: "34a Manas St, Almaty",
    addressRu: "ул. Манаса, 34а, Алматы",
    studentsCount: 4000,
    hasMilitaryDept: false,
    hasHostel: true,
    accreditation: "ABET",
    universityType: "PRIVATE",
  },
  {
    id: "11",
    name: "Kazakh National Medical University",
    nameRu: "Казахский национальный медицинский университет им. Асфендиярова",
    slug: "kaznmu",
    city: "almaty",
    cityRu: "Алматы",
    description: "Premier medical university in Kazakhstan.",
    descriptionRu: "Ведущий медицинский университет Казахстана. Готовит врачей всех специальностей по международным стандартам.",
    logoUrl: "https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=200&h=200&fit=crop",
    coverImageUrl: "https://images.unsplash.com/photo-1538108149393-fbbd81895907?w=1200&h=600&fit=crop",
    ranking: 11,
    foundedYear: 1931,
    website: "https://kaznmu.kz",
    email: "info@kaznmu.kz",
    phone: "+7 727 292 7938",
    address: "94 Tole Bi St, Almaty",
    addressRu: "ул. Толе би, 94, Алматы",
    studentsCount: 9000,
    hasMilitaryDept: true,
    hasHostel: true,
    accreditation: "WFME",
    universityType: "NATIONAL",
  },
  {
    id: "12",
    name: "Karaganda State Technical University",
    nameRu: "Карагандинский государственный технический университет",
    slug: "kstu",
    city: "karaganda",
    cityRu: "Караганда",
    description: "Leading technical university in Central Kazakhstan.",
    descriptionRu: "Ведущий технический университет Центрального Казахстана. Специализируется на горном деле и машиностроении.",
    logoUrl: "https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=200&h=200&fit=crop",
    coverImageUrl: "https://images.unsplash.com/photo-1562774053-701939374585?w=1200&h=600&fit=crop",
    ranking: 12,
    foundedYear: 1953,
    website: "https://kstu.kz",
    email: "info@kstu.kz",
    phone: "+7 7212 56 5935",
    address: "56 Nazarbayev Ave, Karaganda",
    addressRu: "пр. Назарбаева, 56, Караганда",
    studentsCount: 8000,
    hasMilitaryDept: true,
    hasHostel: true,
    accreditation: "IQAA",
    universityType: "PUBLIC",
  },
  {
    id: "13",
    name: "M. Auezov South Kazakhstan University",
    nameRu: "Южно-Казахстанский университет им. М. Ауэзова",
    slug: "sksu",
    city: "shymkent",
    cityRu: "Шымкент",
    description: "Major university in South Kazakhstan.",
    descriptionRu: "Крупный университет Южного Казахстана. Многопрофильный вуз с широким спектром специальностей.",
    logoUrl: "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=200&h=200&fit=crop",
    coverImageUrl: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=1200&h=600&fit=crop",
    ranking: 13,
    foundedYear: 1943,
    website: "https://auezov.edu.kz",
    email: "info@auezov.edu.kz",
    phone: "+7 7252 40 0030",
    address: "5 Tauke Khan Ave, Shymkent",
    addressRu: "пр. Тауке хана, 5, Шымкент",
    studentsCount: 15000,
    hasMilitaryDept: true,
    hasHostel: true,
    accreditation: "IQAA",
    universityType: "PUBLIC",
  },
  {
    id: "14",
    name: "Aktobe Regional University",
    nameRu: "Актюбинский региональный университет им. К. Жубанова",
    slug: "arsu",
    city: "aktobe",
    cityRu: "Актобе",
    description: "Regional university serving Western Kazakhstan.",
    descriptionRu: "Региональный университет, обслуживающий Западный Казахстан. Готовит педагогов и специалистов для региона.",
    logoUrl: "https://images.unsplash.com/photo-1568792923760-d70635a89fdc?w=200&h=200&fit=crop",
    coverImageUrl: "https://images.unsplash.com/photo-1607237138185-eedd9c632b0b?w=1200&h=600&fit=crop",
    ranking: 14,
    foundedYear: 1966,
    website: "https://arsu.kz",
    email: "info@arsu.kz",
    phone: "+7 7132 56 3616",
    address: "34 Moldagulova Ave, Aktobe",
    addressRu: "пр. Молдагуловой, 34, Актобе",
    studentsCount: 7000,
    hasMilitaryDept: true,
    hasHostel: true,
    accreditation: "IQAA",
    universityType: "PUBLIC",
  },
  {
    id: "15",
    name: "Pavlodar State University",
    nameRu: "Павлодарский государственный университет им. С. Торайгырова",
    slug: "psu",
    city: "pavlodar",
    cityRu: "Павлодар",
    description: "Main university in Pavlodar region.",
    descriptionRu: "Основной университет Павлодарской области. Многопрофильный вуз с акцентом на инженерные и педагогические специальности.",
    logoUrl: "https://images.unsplash.com/photo-1519452635265-7b1fbfd1e4e0?w=200&h=200&fit=crop",
    coverImageUrl: "https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?w=1200&h=600&fit=crop",
    ranking: 15,
    foundedYear: 1960,
    website: "https://psu.kz",
    email: "info@psu.kz",
    phone: "+7 7182 67 3644",
    address: "64 Lomov St, Pavlodar",
    addressRu: "ул. Ломова, 64, Павлодар",
    studentsCount: 9000,
    hasMilitaryDept: true,
    hasHostel: true,
    accreditation: "IQAA",
    universityType: "PUBLIC",
  },
  {
    id: "16",
    name: "D. Serikbayev East Kazakhstan Technical University",
    nameRu: "Восточно-Казахстанский технический университет им. Д. Серикбаева",
    slug: "ektu",
    city: "ust-kamenogorsk",
    cityRu: "Усть-Каменогорск",
    description: "Technical university in East Kazakhstan.",
    descriptionRu: "Технический университет Восточного Казахстана. Специализируется на металлургии и машиностроении.",
    logoUrl: "https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=200&h=200&fit=crop",
    coverImageUrl: "https://images.unsplash.com/photo-1562774053-701939374585?w=1200&h=600&fit=crop",
    ranking: 16,
    foundedYear: 1958,
    website: "https://ektu.kz",
    email: "info@ektu.kz",
    phone: "+7 7232 54 0580",
    address: "69 Protozanov St, Ust-Kamenogorsk",
    addressRu: "ул. Протозанова, 69, Усть-Каменогорск",
    studentsCount: 6000,
    hasMilitaryDept: true,
    hasHostel: true,
    accreditation: "IQAA",
    universityType: "PUBLIC",
  },
  {
    id: "17",
    name: "Taraz State University",
    nameRu: "Таразский государственный университет им. М.Х. Дулати",
    slug: "tsu",
    city: "taraz",
    cityRu: "Тараз",
    description: "Major university in Zhambyl region.",
    descriptionRu: "Крупный университет Жамбылской области. Готовит специалистов для химической и пищевой промышленности региона.",
    logoUrl: "https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=200&h=200&fit=crop",
    coverImageUrl: "https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=1200&h=600&fit=crop",
    ranking: 17,
    foundedYear: 1998,
    website: "https://dulaty.kz",
    email: "info@dulaty.kz",
    phone: "+7 7262 43 4005",
    address: "60 Tole Bi St, Taraz",
    addressRu: "ул. Толе би, 60, Тараз",
    studentsCount: 12000,
    hasMilitaryDept: true,
    hasHostel: true,
    accreditation: "IQAA",
    universityType: "PUBLIC",
  },
  {
    id: "18",
    name: "Korkyt Ata Kyzylorda University",
    nameRu: "Кызылординский университет им. Коркыт Ата",
    slug: "korkyt-ata",
    city: "kyzylorda",
    cityRu: "Кызылорда",
    description: "Regional university in Kyzylorda.",
    descriptionRu: "Региональный университет в Кызылорде. Готовит кадры для нефтегазовой отрасли и сельского хозяйства.",
    logoUrl: "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=200&h=200&fit=crop",
    coverImageUrl: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=1200&h=600&fit=crop",
    ranking: 18,
    foundedYear: 1937,
    website: "https://korkyt.kz",
    email: "info@korkyt.kz",
    phone: "+7 7242 26 1717",
    address: "29a Aiteke Bi St, Kyzylorda",
    addressRu: "ул. Айтеке би, 29а, Кызылорда",
    studentsCount: 6000,
    hasMilitaryDept: true,
    hasHostel: true,
    accreditation: "IQAA",
    universityType: "PUBLIC",
  },
  {
    id: "19",
    name: "West Kazakhstan University",
    nameRu: "Западно-Казахстанский университет им. М. Утемисова",
    slug: "wku",
    city: "oral",
    cityRu: "Уральск",
    description: "Main university in West Kazakhstan region.",
    descriptionRu: "Главный университет Западно-Казахстанской области. Многопрофильный вуз с педагогическим уклоном.",
    logoUrl: "https://images.unsplash.com/photo-1519452635265-7b1fbfd1e4e0?w=200&h=200&fit=crop",
    coverImageUrl: "https://images.unsplash.com/photo-1607237138185-eedd9c632b0b?w=1200&h=600&fit=crop",
    ranking: 19,
    foundedYear: 1932,
    website: "https://wksu.kz",
    email: "info@wksu.kz",
    phone: "+7 7112 51 0857",
    address: "162 Dostyk Ave, Oral",
    addressRu: "пр. Достык, 162, Уральск",
    studentsCount: 7500,
    hasMilitaryDept: true,
    hasHostel: true,
    accreditation: "IQAA",
    universityType: "PUBLIC",
  },
  {
    id: "20",
    name: "North Kazakhstan University",
    nameRu: "Северо-Казахстанский университет им. М. Козыбаева",
    slug: "nksu",
    city: "petropavlovsk",
    cityRu: "Петропавловск",
    description: "University serving North Kazakhstan.",
    descriptionRu: "Университет Северного Казахстана. Готовит педагогов и специалистов сельского хозяйства.",
    logoUrl: "https://images.unsplash.com/photo-1568792923760-d70635a89fdc?w=200&h=200&fit=crop",
    coverImageUrl: "https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?w=1200&h=600&fit=crop",
    ranking: 20,
    foundedYear: 1937,
    website: "https://nksu.kz",
    email: "info@nksu.kz",
    phone: "+7 7152 49 3309",
    address: "86 Pushkin St, Petropavlovsk",
    addressRu: "ул. Пушкина, 86, Петропавловск",
    studentsCount: 5500,
    hasMilitaryDept: true,
    hasHostel: true,
    accreditation: "IQAA",
    universityType: "PUBLIC",
  },
  {
    id: "21",
    name: "Caspian University of Technologies and Engineering",
    nameRu: "Каспийский университет технологий и инжиниринга им. Ш. Есенова",
    slug: "yessenov",
    city: "aktau",
    cityRu: "Актау",
    description: "Technical university in Mangystau region.",
    descriptionRu: "Технический университет Мангистауской области. Специализируется на нефтегазовой отрасли.",
    logoUrl: "https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=200&h=200&fit=crop",
    coverImageUrl: "https://images.unsplash.com/photo-1562774053-701939374585?w=1200&h=600&fit=crop",
    ranking: 21,
    foundedYear: 1975,
    website: "https://yu.edu.kz",
    email: "info@yu.edu.kz",
    phone: "+7 7292 33 9770",
    address: "32 Microdistrict, Aktau",
    addressRu: "32 мкр., Актау",
    studentsCount: 7000,
    hasMilitaryDept: true,
    hasHostel: true,
    accreditation: "IQAA",
    universityType: "PUBLIC",
  },
  {
    id: "22",
    name: "Atyrau University of Oil and Gas",
    nameRu: "Атырауский университет нефти и газа им. С. Утебаева",
    slug: "aogu",
    city: "atyrau",
    cityRu: "Атырау",
    description: "Specialized oil and gas university.",
    descriptionRu: "Специализированный нефтегазовый университет. Готовит кадры для крупнейших нефтяных компаний Казахстана.",
    logoUrl: "https://images.unsplash.com/photo-1518611012118-696072aa579a?w=200&h=200&fit=crop",
    coverImageUrl: "https://images.unsplash.com/photo-1497435334941-8c899ee9e8e9?w=1200&h=600&fit=crop",
    ranking: 22,
    foundedYear: 1999,
    website: "https://aogu.edu.kz",
    email: "info@aogu.edu.kz",
    phone: "+7 7122 35 4010",
    address: "45 Azattyk Ave, Atyrau",
    addressRu: "пр. Азаттык, 45, Атырау",
    studentsCount: 4500,
    hasMilitaryDept: false,
    hasHostel: true,
    accreditation: "IQAA",
    universityType: "PUBLIC",
  },
  {
    id: "23",
    name: "Kostanay State University",
    nameRu: "Костанайский государственный университет им. А. Байтурсынова",
    slug: "ksu-kostanay",
    city: "kostanay",
    cityRu: "Костанай",
    description: "State university in Kostanay region.",
    descriptionRu: "Государственный университет Костанайской области. Сильные аграрные и педагогические факультеты.",
    logoUrl: "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=200&h=200&fit=crop",
    coverImageUrl: "https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=1200&h=600&fit=crop",
    ranking: 23,
    foundedYear: 1939,
    website: "https://ksu.edu.kz",
    email: "info@ksu.edu.kz",
    phone: "+7 7142 51 1199",
    address: "47 Baitursynov St, Kostanay",
    addressRu: "ул. Байтурсынова, 47, Костанай",
    studentsCount: 8000,
    hasMilitaryDept: true,
    hasHostel: true,
    accreditation: "IQAA",
    universityType: "PUBLIC",
  },
  {
    id: "24",
    name: "Semey State Medical University",
    nameRu: "Государственный медицинский университет г. Семей",
    slug: "ssmu",
    city: "semey",
    cityRu: "Семей",
    description: "Medical university in Semey.",
    descriptionRu: "Медицинский университет в Семее. Один из старейших медицинских вузов страны.",
    logoUrl: "https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=200&h=200&fit=crop",
    coverImageUrl: "https://images.unsplash.com/photo-1538108149393-fbbd81895907?w=1200&h=600&fit=crop",
    ranking: 24,
    foundedYear: 1953,
    website: "https://semeymeduni.kz",
    email: "info@semeymeduni.kz",
    phone: "+7 7222 56 9811",
    address: "103 Abai St, Semey",
    addressRu: "ул. Абая, 103, Семей",
    studentsCount: 5000,
    hasMilitaryDept: true,
    hasHostel: true,
    accreditation: "WFME",
    universityType: "PUBLIC",
  },
  {
    id: "25",
    name: "Khoja Akhmet Yassawi International University",
    nameRu: "Международный казахско-турецкий университет им. Х.А. Ясави",
    slug: "iktu",
    city: "turkestan",
    cityRu: "Туркестан",
    description: "International university in historic Turkestan.",
    descriptionRu: "Международный университет в историческом Туркестане. Совместный проект Казахстана и Турции.",
    logoUrl: "https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=200&h=200&fit=crop",
    coverImageUrl: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=1200&h=600&fit=crop",
    ranking: 25,
    foundedYear: 1991,
    website: "https://ayu.edu.kz",
    email: "info@ayu.edu.kz",
    phone: "+7 7253 36 3640",
    address: "1 Bekzat Sattarkhanov Ave, Turkestan",
    addressRu: "пр. Бекзата Саттарханова, 1, Туркестан",
    studentsCount: 11000,
    hasMilitaryDept: true,
    hasHostel: true,
    accreditation: "IQAA",
    universityType: "INTERNATIONAL",
  },
  // Adding more universities to reach 50+
  {
    id: "26",
    name: "Almaty Technological University",
    nameRu: "Алматинский технологический университет",
    slug: "atu",
    city: "almaty",
    cityRu: "Алматы",
    description: "Technological university specializing in food and light industry.",
    descriptionRu: "Технологический университет, специализирующийся на пищевой и легкой промышленности.",
    logoUrl: "https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=200&h=200&fit=crop",
    coverImageUrl: "https://images.unsplash.com/photo-1562774053-701939374585?w=1200&h=600&fit=crop",
    ranking: 26,
    foundedYear: 1957,
    website: "https://atu.kz",
    email: "info@atu.kz",
    phone: "+7 727 293 5261",
    studentsCount: 6000,
    hasMilitaryDept: true,
    hasHostel: true,
    universityType: "PUBLIC",
  },
  {
    id: "27",
    name: "Abai Kazakh National Pedagogical University",
    nameRu: "Казахский национальный педагогический университет им. Абая",
    slug: "kaznpu",
    city: "almaty",
    cityRu: "Алматы",
    description: "Leading pedagogical university in Kazakhstan.",
    descriptionRu: "Ведущий педагогический университет Казахстана. Готовит учителей для всей страны.",
    logoUrl: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=200&h=200&fit=crop",
    coverImageUrl: "https://images.unsplash.com/photo-1509062522246-3755977927d7?w=1200&h=600&fit=crop",
    ranking: 27,
    foundedYear: 1928,
    website: "https://kaznpu.kz",
    email: "info@kaznpu.kz",
    phone: "+7 727 291 8242",
    studentsCount: 14000,
    hasMilitaryDept: true,
    hasHostel: true,
    universityType: "NATIONAL",
  },
  {
    id: "28",
    name: "Kazakh National Academy of Arts",
    nameRu: "Казахская национальная академия искусств им. Т. Жургенова",
    slug: "kaznai",
    city: "almaty",
    cityRu: "Алматы",
    description: "Premier arts and culture academy.",
    descriptionRu: "Ведущая академия искусств и культуры. Готовит актеров, режиссеров и деятелей искусства.",
    logoUrl: "https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?w=200&h=200&fit=crop",
    coverImageUrl: "https://images.unsplash.com/photo-1518998053901-5348d3961a04?w=1200&h=600&fit=crop",
    ranking: 28,
    foundedYear: 1978,
    website: "https://kaznai.kz",
    email: "info@kaznai.kz",
    phone: "+7 727 261 6594",
    studentsCount: 2000,
    hasMilitaryDept: false,
    hasHostel: true,
    universityType: "NATIONAL",
  },
  {
    id: "29",
    name: "Kazakh University of Economics, Finance and International Trade",
    nameRu: "Казахский университет экономики, финансов и международной торговли",
    slug: "kuef",
    city: "astana",
    cityRu: "Астана",
    description: "Specialized economics and finance university.",
    descriptionRu: "Специализированный университет экономики и финансов в столице.",
    logoUrl: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=200&h=200&fit=crop",
    coverImageUrl: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1200&h=600&fit=crop",
    ranking: 29,
    foundedYear: 2008,
    website: "https://kuef.kz",
    email: "info@kuef.kz",
    phone: "+7 7172 41 3412",
    studentsCount: 4000,
    hasMilitaryDept: false,
    hasHostel: true,
    universityType: "PUBLIC",
  },
  {
    id: "30",
    name: "Kazakh Humanitarian Law Innovative University",
    nameRu: "Казахский гуманитарно-юридический инновационный университет",
    slug: "khu",
    city: "semey",
    cityRu: "Семей",
    description: "Humanitarian and law focused university.",
    descriptionRu: "Университет с гуманитарным и юридическим уклоном.",
    logoUrl: "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=200&h=200&fit=crop",
    coverImageUrl: "https://images.unsplash.com/photo-1505664194779-8beaceb93744?w=1200&h=600&fit=crop",
    ranking: 30,
    foundedYear: 1994,
    website: "https://khu.kz",
    email: "info@khu.kz",
    phone: "+7 7222 52 4521",
    studentsCount: 3500,
    hasMilitaryDept: false,
    hasHostel: true,
    universityType: "PRIVATE",
  },
  {
    id: "31",
    name: "University of International Business",
    nameRu: "Университет международного бизнеса",
    slug: "uib",
    city: "almaty",
    cityRu: "Алматы",
    description: "Business focused private university.",
    descriptionRu: "Частный бизнес-университет с международными программами.",
    logoUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop",
    coverImageUrl: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200&h=600&fit=crop",
    ranking: 31,
    foundedYear: 1992,
    website: "https://uib.kz",
    email: "info@uib.kz",
    phone: "+7 727 259 8081",
    studentsCount: 4500,
    hasMilitaryDept: false,
    hasHostel: true,
    universityType: "PRIVATE",
  },
  {
    id: "32",
    name: "Kazakh-Russian International University",
    nameRu: "Казахстанско-Российский международный университет",
    slug: "kriu",
    city: "aktobe",
    cityRu: "Актобе",
    description: "Joint Kazakh-Russian international university.",
    descriptionRu: "Совместный казахстанско-российский международный университет.",
    logoUrl: "https://images.unsplash.com/photo-1519452635265-7b1fbfd1e4e0?w=200&h=200&fit=crop",
    coverImageUrl: "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=1200&h=600&fit=crop",
    ranking: 32,
    foundedYear: 2005,
    website: "https://kriu.kz",
    email: "info@kriu.kz",
    phone: "+7 7132 21 4521",
    studentsCount: 2500,
    hasMilitaryDept: false,
    hasHostel: true,
    universityType: "INTERNATIONAL",
  },
  {
    id: "33",
    name: "Academy of Logistics and Transport",
    nameRu: "Академия логистики и транспорта",
    slug: "alt",
    city: "almaty",
    cityRu: "Алматы",
    description: "Specialized transport and logistics academy.",
    descriptionRu: "Специализированная академия транспорта и логистики.",
    logoUrl: "https://images.unsplash.com/photo-1494412574643-ff11b0a5c1c3?w=200&h=200&fit=crop",
    coverImageUrl: "https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=1200&h=600&fit=crop",
    ranking: 33,
    foundedYear: 1931,
    website: "https://alt.edu.kz",
    email: "info@alt.edu.kz",
    phone: "+7 727 292 0935",
    studentsCount: 5500,
    hasMilitaryDept: true,
    hasHostel: true,
    universityType: "PUBLIC",
  },
  {
    id: "34",
    name: "Narxoz University",
    nameRu: "Университет Нархоз",
    slug: "narxoz",
    city: "almaty",
    cityRu: "Алматы",
    description: "Economics and business oriented university.",
    descriptionRu: "Университет с экономическим и бизнес-уклоном.",
    logoUrl: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=200&h=200&fit=crop",
    coverImageUrl: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1200&h=600&fit=crop",
    ranking: 34,
    foundedYear: 1963,
    website: "https://narxoz.kz",
    email: "info@narxoz.kz",
    phone: "+7 727 377 1111",
    studentsCount: 7000,
    hasMilitaryDept: false,
    hasHostel: true,
    universityType: "PRIVATE",
  },
  {
    id: "35",
    name: "Kazakh Academy of Sports and Tourism",
    nameRu: "Казахская академия спорта и туризма",
    slug: "kazast",
    city: "almaty",
    cityRu: "Алматы",
    description: "Sports and tourism focused academy.",
    descriptionRu: "Академия спорта и туризма. Готовит спортсменов и специалистов туриндустрии.",
    logoUrl: "https://images.unsplash.com/photo-1461896836934- voices-e74-e95a?w=200&h=200&fit=crop",
    coverImageUrl: "https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=1200&h=600&fit=crop",
    ranking: 35,
    foundedYear: 1944,
    website: "https://kazast.kz",
    email: "info@kazast.kz",
    phone: "+7 727 292 4765",
    studentsCount: 3000,
    hasMilitaryDept: false,
    hasHostel: true,
    universityType: "PUBLIC",
  },
  {
    id: "36",
    name: "Astana Medical University",
    nameRu: "Медицинский университет Астана",
    slug: "amu",
    city: "astana",
    cityRu: "Астана",
    description: "Medical university in the capital.",
    descriptionRu: "Медицинский университет в столице. Современная клиническая база.",
    logoUrl: "https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=200&h=200&fit=crop",
    coverImageUrl: "https://images.unsplash.com/photo-1538108149393-fbbd81895907?w=1200&h=600&fit=crop",
    ranking: 36,
    foundedYear: 1964,
    website: "https://amu.kz",
    email: "info@amu.kz",
    phone: "+7 7172 53 9434",
    studentsCount: 6000,
    hasMilitaryDept: true,
    hasHostel: true,
    universityType: "PUBLIC",
  },
  {
    id: "37",
    name: "Karaganda Medical University",
    nameRu: "Карагандинский медицинский университет",
    slug: "kgmu",
    city: "karaganda",
    cityRu: "Караганда",
    description: "Medical university in Karaganda.",
    descriptionRu: "Медицинский университет в Караганде с богатой историей.",
    logoUrl: "https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=200&h=200&fit=crop",
    coverImageUrl: "https://images.unsplash.com/photo-1538108149393-fbbd81895907?w=1200&h=600&fit=crop",
    ranking: 37,
    foundedYear: 1950,
    website: "https://kgmu.kz",
    email: "info@kgmu.kz",
    phone: "+7 7212 51 3479",
    studentsCount: 5500,
    hasMilitaryDept: true,
    hasHostel: true,
    universityType: "PUBLIC",
  },
  {
    id: "38",
    name: "South Kazakhstan Medical Academy",
    nameRu: "Южно-Казахстанская медицинская академия",
    slug: "skma",
    city: "shymkent",
    cityRu: "Шымкент",
    description: "Medical academy in South Kazakhstan.",
    descriptionRu: "Медицинская академия Южного Казахстана.",
    logoUrl: "https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=200&h=200&fit=crop",
    coverImageUrl: "https://images.unsplash.com/photo-1538108149393-fbbd81895907?w=1200&h=600&fit=crop",
    ranking: 38,
    foundedYear: 1979,
    website: "https://skma.kz",
    email: "info@skma.kz",
    phone: "+7 7252 53 9876",
    studentsCount: 4500,
    hasMilitaryDept: true,
    hasHostel: true,
    universityType: "PUBLIC",
  },
  {
    id: "39",
    name: "West Kazakhstan Medical University",
    nameRu: "Западно-Казахстанский медицинский университет им. М. Оспанова",
    slug: "wkmu",
    city: "aktobe",
    cityRu: "Актобе",
    description: "Medical university in West Kazakhstan.",
    descriptionRu: "Медицинский университет Западного Казахстана.",
    logoUrl: "https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=200&h=200&fit=crop",
    coverImageUrl: "https://images.unsplash.com/photo-1538108149393-fbbd81895907?w=1200&h=600&fit=crop",
    ranking: 39,
    foundedYear: 1957,
    website: "https://zkgmu.kz",
    email: "info@zkgmu.kz",
    phone: "+7 7132 54 1234",
    studentsCount: 4000,
    hasMilitaryDept: true,
    hasHostel: true,
    universityType: "PUBLIC",
  },
  {
    id: "40",
    name: "Kazakh National Conservatory",
    nameRu: "Казахская национальная консерватория им. Курмангазы",
    slug: "kazcon",
    city: "almaty",
    cityRu: "Алматы",
    description: "Premier music conservatory.",
    descriptionRu: "Ведущая музыкальная консерватория страны.",
    logoUrl: "https://images.unsplash.com/photo-1507838153414-b4b713384a76?w=200&h=200&fit=crop",
    coverImageUrl: "https://images.unsplash.com/photo-1514320291840-2e0a9bf2a9ae?w=1200&h=600&fit=crop",
    ranking: 40,
    foundedYear: 1944,
    website: "https://kazcons.kz",
    email: "info@kazcons.kz",
    phone: "+7 727 261 7895",
    studentsCount: 1200,
    hasMilitaryDept: false,
    hasHostel: true,
    universityType: "NATIONAL",
  },
  {
    id: "41",
    name: "Turan University",
    nameRu: "Университет Туран",
    slug: "turan",
    city: "almaty",
    cityRu: "Алматы",
    description: "Private multidisciplinary university.",
    descriptionRu: "Частный многопрофильный университет.",
    logoUrl: "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=200&h=200&fit=crop",
    coverImageUrl: "https://images.unsplash.com/photo-1562774053-701939374585?w=1200&h=600&fit=crop",
    ranking: 41,
    foundedYear: 1992,
    website: "https://turan-edu.kz",
    email: "info@turan-edu.kz",
    phone: "+7 727 260 4042",
    studentsCount: 5000,
    hasMilitaryDept: false,
    hasHostel: true,
    universityType: "PRIVATE",
  },
  {
    id: "42",
    name: "Innovative University of Eurasia",
    nameRu: "Инновационный Евразийский университет",
    slug: "ieu",
    city: "pavlodar",
    cityRu: "Павлодар",
    description: "Innovative private university in Pavlodar.",
    descriptionRu: "Инновационный частный университет в Павлодаре.",
    logoUrl: "https://images.unsplash.com/photo-1519452635265-7b1fbfd1e4e0?w=200&h=200&fit=crop",
    coverImageUrl: "https://images.unsplash.com/photo-1607237138185-eedd9c632b0b?w=1200&h=600&fit=crop",
    ranking: 42,
    foundedYear: 1997,
    website: "https://ineu.kz",
    email: "info@ineu.kz",
    phone: "+7 7182 65 1234",
    studentsCount: 4000,
    hasMilitaryDept: false,
    hasHostel: true,
    universityType: "PRIVATE",
  },
  {
    id: "43",
    name: "Central Asian University",
    nameRu: "Центрально-Азиатский университет",
    slug: "cau",
    city: "almaty",
    cityRu: "Алматы",
    description: "Private university with Central Asian focus.",
    descriptionRu: "Частный университет с центральноазиатским фокусом.",
    logoUrl: "https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=200&h=200&fit=crop",
    coverImageUrl: "https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=1200&h=600&fit=crop",
    ranking: 43,
    foundedYear: 1997,
    website: "https://cau.kz",
    email: "info@cau.kz",
    phone: "+7 727 260 7654",
    studentsCount: 2500,
    hasMilitaryDept: false,
    hasHostel: true,
    universityType: "PRIVATE",
  },
  {
    id: "44",
    name: "Almaty Management University",
    nameRu: "Алматы Менеджмент Университет (AlmaU)",
    slug: "almau",
    city: "almaty",
    cityRu: "Алматы",
    description: "Business school focused on management education.",
    descriptionRu: "Бизнес-школа с фокусом на управленческое образование.",
    logoUrl: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=200&h=200&fit=crop",
    coverImageUrl: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200&h=600&fit=crop",
    ranking: 44,
    foundedYear: 1988,
    website: "https://almau.edu.kz",
    email: "info@almau.edu.kz",
    phone: "+7 727 302 2424",
    studentsCount: 3000,
    hasMilitaryDept: false,
    hasHostel: true,
    universityType: "PRIVATE",
  },
  {
    id: "45",
    name: "Bolashak University",
    nameRu: "Университет Болашак",
    slug: "bolashak",
    city: "kyzylorda",
    cityRu: "Кызылорда",
    description: "Private university in Kyzylorda region.",
    descriptionRu: "Частный университет в Кызылординской области.",
    logoUrl: "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=200&h=200&fit=crop",
    coverImageUrl: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=1200&h=600&fit=crop",
    ranking: 45,
    foundedYear: 1993,
    website: "https://bolashak-univer.kz",
    email: "info@bolashak-univer.kz",
    phone: "+7 7242 27 5678",
    studentsCount: 2000,
    hasMilitaryDept: false,
    hasHostel: true,
    universityType: "PRIVATE",
  },
  {
    id: "46",
    name: "Miras University",
    nameRu: "Университет Мирас",
    slug: "miras",
    city: "shymkent",
    cityRu: "Шымкент",
    description: "Private university in South Kazakhstan.",
    descriptionRu: "Частный университет в Южном Казахстане.",
    logoUrl: "https://images.unsplash.com/photo-1519452635265-7b1fbfd1e4e0?w=200&h=200&fit=crop",
    coverImageUrl: "https://images.unsplash.com/photo-1607237138185-eedd9c632b0b?w=1200&h=600&fit=crop",
    ranking: 46,
    foundedYear: 1997,
    website: "https://mirasuniversity.kz",
    email: "info@mirasuniversity.kz",
    phone: "+7 7252 39 8765",
    studentsCount: 3500,
    hasMilitaryDept: false,
    hasHostel: true,
    universityType: "PRIVATE",
  },
  {
    id: "47",
    name: "Shakarim University",
    nameRu: "Университет Шакарима",
    slug: "shakarim",
    city: "semey",
    cityRu: "Семей",
    description: "State university named after Shakarim.",
    descriptionRu: "Государственный университет имени Шакарима.",
    logoUrl: "https://images.unsplash.com/photo-1568792923760-d70635a89fdc?w=200&h=200&fit=crop",
    coverImageUrl: "https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?w=1200&h=600&fit=crop",
    ranking: 47,
    foundedYear: 1990,
    website: "https://shakarim.kz",
    email: "info@shakarim.kz",
    phone: "+7 7222 35 6789",
    studentsCount: 8000,
    hasMilitaryDept: true,
    hasHostel: true,
    universityType: "PUBLIC",
  },
  {
    id: "48",
    name: "Rudny Industrial Institute",
    nameRu: "Рудненский индустриальный институт",
    slug: "rii",
    city: "kostanay",
    cityRu: "Костанай",
    description: "Industrial technical institute in Rudny.",
    descriptionRu: "Индустриально-технический институт в Рудном.",
    logoUrl: "https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=200&h=200&fit=crop",
    coverImageUrl: "https://images.unsplash.com/photo-1562774053-701939374585?w=1200&h=600&fit=crop",
    ranking: 48,
    foundedYear: 1964,
    website: "https://rii.kz",
    email: "info@rii.kz",
    phone: "+7 71431 5 6543",
    studentsCount: 3000,
    hasMilitaryDept: true,
    hasHostel: true,
    universityType: "PUBLIC",
  },
  {
    id: "49",
    name: "Ekibastuz Engineering and Technical Institute",
    nameRu: "Екибастузский инженерно-технический институт им. К. Сатпаева",
    slug: "eeti",
    city: "pavlodar",
    cityRu: "Павлодар",
    description: "Technical institute in Ekibastuz.",
    descriptionRu: "Технический институт в Экибастузе, филиал ENU.",
    logoUrl: "https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=200&h=200&fit=crop",
    coverImageUrl: "https://images.unsplash.com/photo-1562774053-701939374585?w=1200&h=600&fit=crop",
    ranking: 49,
    foundedYear: 1994,
    website: "https://eeti.kz",
    email: "info@eeti.kz",
    phone: "+7 71877 3 4567",
    studentsCount: 2000,
    hasMilitaryDept: false,
    hasHostel: true,
    universityType: "PUBLIC",
  },
  {
    id: "50",
    name: "Zhetysu University",
    nameRu: "Жетысуский университет им. И. Жансугурова",
    slug: "zhetysu",
    city: "almaty",
    cityRu: "Алматинская область",
    description: "Regional university in Taldykorgan.",
    descriptionRu: "Региональный университет в Талдыкоргане.",
    logoUrl: "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=200&h=200&fit=crop",
    coverImageUrl: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=1200&h=600&fit=crop",
    ranking: 50,
    foundedYear: 1972,
    website: "https://zhetysu.edu.kz",
    email: "info@zhetysu.edu.kz",
    phone: "+7 7282 27 1234",
    studentsCount: 6000,
    hasMilitaryDept: true,
    hasHostel: true,
    universityType: "PUBLIC",
  },
];

// Mock Majors Data
export const majors: Major[] = [
  {
    id: "1",
    code: "6B06101",
    name: "Computer Science",
    nameRu: "Информатика",
    description: "Study of computation, algorithms, and programming.",
    descriptionRu: "Изучение вычислений, алгоритмов и программирования.",
    subjectCombination: ["math", "physics"],
    category: "IT",
    riasecTypes: ["I", "R", "C"],
  },
  {
    id: "2",
    code: "6B06102",
    name: "Software Engineering",
    nameRu: "Программная инженерия",
    description: "Design and development of software systems.",
    descriptionRu: "Проектирование и разработка программных систем.",
    subjectCombination: ["math", "physics"],
    category: "IT",
    riasecTypes: ["I", "R", "C"],
  },
  {
    id: "3",
    code: "6B06103",
    name: "Information Systems",
    nameRu: "Информационные системы",
    description: "Management of information technology in organizations.",
    descriptionRu: "Управление информационными технологиями в организациях.",
    subjectCombination: ["math", "physics"],
    category: "IT",
    riasecTypes: ["I", "E", "C"],
  },
  {
    id: "4",
    code: "6B07101",
    name: "Mechanical Engineering",
    nameRu: "Машиностроение",
    description: "Design and manufacturing of mechanical systems.",
    descriptionRu: "Проектирование и производство механических систем.",
    subjectCombination: ["math", "physics"],
    category: "ENGINEERING",
    riasecTypes: ["R", "I", "C"],
  },
  {
    id: "5",
    code: "6B07102",
    name: "Electrical Engineering",
    nameRu: "Электротехника",
    description: "Study of electrical systems and electronics.",
    descriptionRu: "Изучение электрических систем и электроники.",
    subjectCombination: ["math", "physics"],
    category: "ENGINEERING",
    riasecTypes: ["R", "I", "C"],
  },
  {
    id: "6",
    code: "6B07201",
    name: "Oil and Gas Engineering",
    nameRu: "Нефтегазовое дело",
    description: "Extraction and processing of oil and gas resources.",
    descriptionRu: "Добыча и переработка нефтегазовых ресурсов.",
    subjectCombination: ["math", "physics"],
    category: "ENGINEERING",
    riasecTypes: ["R", "I", "E"],
  },
  {
    id: "7",
    code: "6B10101",
    name: "General Medicine",
    nameRu: "Общая медицина",
    description: "Training to become a medical doctor.",
    descriptionRu: "Подготовка врачей общей практики.",
    subjectCombination: ["biology", "chemistry"],
    category: "MEDICINE",
    riasecTypes: ["I", "S", "R"],
  },
  {
    id: "8",
    code: "6B10102",
    name: "Dentistry",
    nameRu: "Стоматология",
    description: "Study of oral health and dental care.",
    descriptionRu: "Изучение здоровья полости рта и стоматологической помощи.",
    subjectCombination: ["biology", "chemistry"],
    category: "MEDICINE",
    riasecTypes: ["I", "S", "R"],
  },
  {
    id: "9",
    code: "6B10103",
    name: "Pharmacy",
    nameRu: "Фармация",
    description: "Study of medications and pharmaceutical sciences.",
    descriptionRu: "Изучение лекарственных препаратов и фармацевтических наук.",
    subjectCombination: ["biology", "chemistry"],
    category: "MEDICINE",
    riasecTypes: ["I", "C", "R"],
  },
  {
    id: "10",
    code: "6B04101",
    name: "Economics",
    nameRu: "Экономика",
    description: "Study of economic systems and financial markets.",
    descriptionRu: "Изучение экономических систем и финансовых рынков.",
    subjectCombination: ["math", "geography"],
    category: "BUSINESS",
    riasecTypes: ["E", "I", "C"],
  },
  {
    id: "11",
    code: "6B04102",
    name: "Finance",
    nameRu: "Финансы",
    description: "Management of money and investments.",
    descriptionRu: "Управление деньгами и инвестициями.",
    subjectCombination: ["math", "geography"],
    category: "BUSINESS",
    riasecTypes: ["E", "C", "I"],
  },
  {
    id: "12",
    code: "6B04103",
    name: "Management",
    nameRu: "Менеджмент",
    description: "Leadership and organizational management.",
    descriptionRu: "Лидерство и управление организациями.",
    subjectCombination: ["math", "geography"],
    category: "BUSINESS",
    riasecTypes: ["E", "S", "C"],
  },
  {
    id: "13",
    code: "6B12101",
    name: "Jurisprudence",
    nameRu: "Юриспруденция",
    description: "Study of law and legal systems.",
    descriptionRu: "Изучение права и правовых систем.",
    subjectCombination: ["history", "world_history"],
    category: "LAW",
    riasecTypes: ["E", "S", "I"],
  },
  {
    id: "14",
    code: "6B02301",
    name: "Philology",
    nameRu: "Филология",
    description: "Study of language and literature.",
    descriptionRu: "Изучение языка и литературы.",
    subjectCombination: ["kazakh", "literature"],
    category: "HUMANITIES",
    riasecTypes: ["A", "I", "S"],
  },
  {
    id: "15",
    code: "6B02302",
    name: "History",
    nameRu: "История",
    description: "Study of past events and civilizations.",
    descriptionRu: "Изучение прошлых событий и цивилизаций.",
    subjectCombination: ["history", "world_history"],
    category: "HUMANITIES",
    riasecTypes: ["I", "A", "S"],
  },
  {
    id: "16",
    code: "6B05101",
    name: "Biology",
    nameRu: "Биология",
    description: "Study of living organisms.",
    descriptionRu: "Изучение живых организмов.",
    subjectCombination: ["biology", "chemistry"],
    category: "NATURAL_SCIENCES",
    riasecTypes: ["I", "R", "A"],
  },
  {
    id: "17",
    code: "6B05102",
    name: "Chemistry",
    nameRu: "Химия",
    description: "Study of matter and chemical reactions.",
    descriptionRu: "Изучение материи и химических реакций.",
    subjectCombination: ["chemistry", "math"],
    category: "NATURAL_SCIENCES",
    riasecTypes: ["I", "R", "C"],
  },
  {
    id: "18",
    code: "6B02101",
    name: "Design",
    nameRu: "Дизайн",
    description: "Creative design and visual arts.",
    descriptionRu: "Креативный дизайн и визуальное искусство.",
    subjectCombination: ["kazakh", "world_history"],
    category: "ARTS",
    riasecTypes: ["A", "R", "E"],
  },
  {
    id: "19",
    code: "6B01101",
    name: "Pedagogy and Psychology",
    nameRu: "Педагогика и психология",
    description: "Teaching methods and human psychology.",
    descriptionRu: "Методы обучения и психология человека.",
    subjectCombination: ["biology", "kazakh"],
    category: "EDUCATION",
    riasecTypes: ["S", "I", "A"],
  },
  {
    id: "20",
    code: "6B08101",
    name: "Agronomy",
    nameRu: "Агрономия",
    description: "Study of crop production and soil management.",
    descriptionRu: "Изучение растениеводства и управления почвами.",
    subjectCombination: ["biology", "chemistry"],
    category: "AGRICULTURE",
    riasecTypes: ["R", "I", "C"],
  },
];

// RIASEC Quiz Questions (30 questions)
export const quizQuestions: QuizQuestion[] = [
  // Realistic (R) - 5 questions
  { id: 1, text: "Мне нравится работать с инструментами и техникой", type: "R" },
  { id: 2, text: "Я предпочитаю практическую работу теоретической", type: "R" },
  { id: 3, text: "Мне интересно собирать и ремонтировать вещи", type: "R" },
  { id: 4, text: "Я люблю работать на свежем воздухе", type: "R" },
  { id: 5, text: "Мне нравится физическая активность в работе", type: "R" },

  // Investigative (I) - 5 questions
  { id: 6, text: "Мне нравится решать сложные задачи и головоломки", type: "I" },
  { id: 7, text: "Я люблю анализировать информацию и данные", type: "I" },
  { id: 8, text: "Мне интересно проводить эксперименты и исследования", type: "I" },
  { id: 9, text: "Я предпочитаю работать самостоятельно над сложными проектами", type: "I" },
  { id: 10, text: "Мне нравится изучать научные теории", type: "I" },

  // Artistic (A) - 5 questions
  { id: 11, text: "Мне нравится выражать себя через творчество", type: "A" },
  { id: 12, text: "Я ценю оригинальность и нестандартное мышление", type: "A" },
  { id: 13, text: "Мне интересны музыка, искусство или литература", type: "A" },
  { id: 14, text: "Я предпочитаю свободный график работы", type: "A" },
  { id: 15, text: "Мне нравится придумывать новые идеи и концепции", type: "A" },

  // Social (S) - 5 questions
  { id: 16, text: "Мне нравится помогать другим людям", type: "S" },
  { id: 17, text: "Я хорошо работаю в команде", type: "S" },
  { id: 18, text: "Мне интересно обучать и наставлять других", type: "S" },
  { id: 19, text: "Я легко нахожу общий язык с разными людьми", type: "S" },
  { id: 20, text: "Мне важно, чтобы моя работа приносила пользу обществу", type: "S" },

  // Enterprising (E) - 5 questions
  { id: 21, text: "Мне нравится руководить и принимать решения", type: "E" },
  { id: 22, text: "Я умею убеждать других в своей точке зрения", type: "E" },
  { id: 23, text: "Мне интересен бизнес и предпринимательство", type: "E" },
  { id: 24, text: "Я не боюсь рисковать ради достижения целей", type: "E" },
  { id: 25, text: "Мне нравится конкурировать и побеждать", type: "E" },

  // Conventional (C) - 5 questions
  { id: 26, text: "Мне нравится работать с цифрами и данными", type: "C" },
  { id: 27, text: "Я предпочитаю четкие правила и инструкции", type: "C" },
  { id: 28, text: "Мне важен порядок и организованность в работе", type: "C" },
  { id: 29, text: "Я внимателен к деталям", type: "C" },
  { id: 30, text: "Мне нравится систематизировать информацию", type: "C" },
];

// RIASEC Type Descriptions
export const riasecDescriptions = {
  R: {
    name: "Реалистичный",
    nameEn: "Realistic",
    description: "Вы предпочитаете практическую работу с конкретными объектами, инструментами и механизмами. Вам подходят профессии, связанные с техникой, строительством, сельским хозяйством.",
    careers: ["Инженер", "Механик", "Архитектор", "Агроном", "Программист"],
    color: "#4CAF50",
  },
  I: {
    name: "Исследовательский",
    nameEn: "Investigative",
    description: "Вы любите анализировать, исследовать и решать сложные задачи. Вам подходят профессии в науке, медицине, IT и аналитике.",
    careers: ["Ученый", "Врач", "Аналитик данных", "Программист", "Фармацевт"],
    color: "#2196F3",
  },
  A: {
    name: "Артистический",
    nameEn: "Artistic",
    description: "Вы творческая личность, которая ценит самовыражение и оригинальность. Вам подходят профессии в искусстве, дизайне, медиа.",
    careers: ["Дизайнер", "Художник", "Журналист", "Режиссер", "Музыкант"],
    color: "#9C27B0",
  },
  S: {
    name: "Социальный",
    nameEn: "Social",
    description: "Вы ориентированы на работу с людьми, помощь и обучение. Вам подходят профессии в образовании, медицине, социальной работе.",
    careers: ["Учитель", "Психолог", "Врач", "Социальный работник", "HR-менеджер"],
    color: "#FF9800",
  },
  E: {
    name: "Предприимчивый",
    nameEn: "Enterprising",
    description: "Вы лидер по натуре, любите управлять, убеждать и достигать целей. Вам подходят профессии в бизнесе, менеджменте, продажах.",
    careers: ["Менеджер", "Предприниматель", "Юрист", "Маркетолог", "Политик"],
    color: "#F44336",
  },
  C: {
    name: "Конвенциональный",
    nameEn: "Conventional",
    description: "Вы цените порядок, точность и систематичность. Вам подходят профессии в финансах, бухгалтерии, администрировании.",
    careers: ["Бухгалтер", "Финансист", "Администратор", "Банкир", "Аудитор"],
    color: "#607D8B",
  },
};
